### ISSUE TITLE
[Feature Request] Support for aws vault secrets backend 

### ISSUE THREAD

**Issue by flyinbutrs** [Nike-Inc/cerberus-management-service#75]
It seems like cerberus could be very useful as a multi-account IAM, generating STS tokens across multiple AWS accounts by IAM role if it supported the AWS Secrets backend in vault. Has this been considered and ruled out, or just not implemented?

I've tried just mounting the AWS backend under the vault secrets/shared/ path, but CMS does not display the vault path at all.

https://www.vaultproject.io/docs/secrets/aws/index.html

**Comment by tlisonbee** [comment]
We haven't really looked at it.  I believe it is new in the last year.

Recently, we've been researching if we could simplify our architecture and rely more on AWS services for handling secrets encryption instead of Vault, e.g. a single micro service using KMS and the AWS Encryption SDK for all encryption,
http://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html

I'm not sure what your use case is for above all of the way.  For temporary user creds, we've seen these tools used:
https://www.onelogin.com/
https://www.okta.com/

Would you mind describing your use case more?

**Comment by flyinbutrs** [comment]
The use case is that we have many accounts to manage, and many lambdas / ECS tasks that need some degree of cross account privilege to manage many accounts. Rather than allowing our systems to use STS directly, we are looking for a system that would allow the folllowing:

- Temporary restricted tokens given out by a central authority
- Full auditing of what IAM entity retrieved what credential and when
- Prevent the need to create many cross account roles, policies, etc within IAM on each account, instead relying on the IAM scope provided at token creation time

Cerberus does not currently support much of this, but I'd like to leverage it because of the layered encryption and authorization that it has already implemented, in addition to the identity validation of each call along the way.

**Comment by tlisonbee** [comment]
I'm not sure if Cerberus is adding much (if any) value over Vault for this kind of use case.

Since Cerberus was released, Vault has added support for IAM auth e.g. "/auth/aws/login" ,
https://www.vaultproject.io/api/auth/aws/index.html

IAM auth in Vault is implemented differently than how Cerberus implemented but performs a similar function.  Have you compared our IAM auth vs. theirs?

I might not be understanding all of the way but for above I think I'd be more tempted to just use Vault directly rather than Cerberus+Vault.

**Comment by flyinbutrs** [comment]
Yeah, I've been reading up on vault's IAM implementation, and I think you might be right. Using Vault directly might be a better fit.
